
/*! @file
 *  This is an example of the PIN tool that demonstrates some basic PIN APIs
 *  and could serve as the starting point for developing your first PIN tool
 */

#include "pin.H"
#include <iostream>
#include <fstream>
#include <stdlib.h>
#include <string.h>
#include <string>

using namespace std;

#define NUM_INSTR_DESTINATIONS 4
#define NUM_INSTR_SOURCES 4

#define SIZE_OF_CALL_INSTRUCTION 5
#define MAX_MEMORY_SIZE 64

#define debug false

typedef struct trace_instr_format
{
    unsigned long long int ip; // instruction pointer (program counter) value

    unsigned char has_mem_is_branch; // does this have memory operands(second bit), is this branch(LSB bit)
    unsigned char branch_taken;      // if so, is this taken

    uint8_t instr_size;

    unsigned char destination_register[NUM_INSTR_DESTINATIONS]; // output registers
    unsigned char source_register[NUM_INSTR_SOURCES];           // input registers

    unsigned long long int *destination_memory_address; // output memory
    unsigned long long int *source_memory_address;      // input memory

    uint8_t *destination_memory_size; // output memory sizes
    uint8_t *source_memory_size;      // input memory sizes

    unsigned char **destination_memory_value; // output memory values
    unsigned char **source_memory_value;      // input memory values

    trace_instr_format()
        : ip(0)
        , has_mem_is_branch(0)
        , branch_taken(0)
        , instr_size(0)
        , destination_memory_address(nullptr)
        , source_memory_address(nullptr)
        , destination_memory_size(nullptr)
        , source_memory_size(nullptr)
        , destination_memory_value(nullptr)
        , source_memory_value(nullptr)
    {
        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
            destination_register[i] = 0;
        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
            source_register[i] = 0;
    }
} trace_instr_format_t;

/* ================================================================== */
// Global variables
/* ================================================================== */

UINT64 instrCount = 0;

FILE *out;

bool output_file_closed = false;
bool tracing_on = false;

trace_instr_format_t curr_instr;
bool skip_curr_instr = false;

// int memoryWriteIndex;
int memOpToDestSlot[NUM_INSTR_SOURCES+NUM_INSTR_DESTINATIONS];      // used only for writes
int skipInstructionCount = 0;   // this count is different knob skip. Just wanted to see which instrs are particularly skipped while tracing because of its memory value size being accesses
int readSkipInstrCount = 0;     // same as above
int writeSkipInstrCount = 0;    // same as above
int unalignedAccessCount = 0;
UINT64 last_func_print_instr = 0;

UINT64 knob_skip_instr_count = UINT64_MAX;
UINT64 knob_trace_instr_count = 0;

// std::map<UINT64, UINT64> read_size_map;
// std::map<UINT64, UINT64> write_size_map;

// std::set<UINT64> read_set;
// std::set<UINT64> write_set;

//   asm volatile("mov $1, %%eax; xchg %%bx, %%bx" ::: "eax"); // preprocessing start
//   asm volatile("mov $2, %%eax; xchg %%bx, %%bx" ::: "eax"); // preprocessing end
//   asm volatile("mov $3, %%eax; xchg %%bx, %%bx" ::: "eax"); // inference pass 1 start
//   asm volatile("mov $4, %%eax; xchg %%bx, %%bx" ::: "eax"); // inference pass 1 end
//   asm volatile("mov $5, %%eax; xchg %%bx, %%bx" ::: "eax"); // inference pass 2 end
// xchg bx,bx is Pin's standard magic NOP — never generated by compilers.
#define PREPROCESSING_START 1
#define PREPROCESSING_END 2
#define INFERENCE_FIRST_PASS_START 3
#define INFERENCE_FIRST_PASS_END 4
#define INFERENCE_SECOND_PASS_END 5

UINT64 phase_instr[6] = {0}; // phase_instr[id] = instrCount when marker id fired
bool   phase_seen[6]  = {false,false,false,false,false,false};

/* ===================================================================== */
// Command line switches
/* ===================================================================== */
KNOB<std::string> KnobOutputFile(KNOB_MODE_WRITEONCE, "pintool", "o", "champsim.trace",
                                 "specify file name for Champsim tracer output");

KNOB<UINT64> KnobSkipInstructions(KNOB_MODE_WRITEONCE, "pintool", "s", "0",
                                  "How many instructions to skip before tracing begins. This wont apply in marker mode");

KNOB<UINT64> KnobTraceInstructions(KNOB_MODE_WRITEONCE, "pintool", "k", "500000000",
                                   "How many instructions to trace. If marker mode is enabled and inference pass end is seen within this value number of instructions, tracing is stopped at inference end marker instr else will be tracing will go on till k instrs");

KNOB<bool> KnobEnableTraceWriting(KNOB_MODE_WRITEONCE, "pintool", "w", "1",
                                    "Specify whether traced instructions should be written to your output file or not");
                                
KNOB<bool> KnobSetMarkerMode(KNOB_MODE_WRITEONCE, "pintool", "m", "0",
                                     "Sets the marker mode value. If true, tracer skips instrs till inference start and trace till inference end marker is found. If start is not found within k instrs, all instrs are skipped. If start is found and end is not found within k instrs after start, tracer traces till k instrs after start and stops. Even when mode is set to false, marker related information will be printed as usual");                                   

/* ===================================================================== */
// Utilities
/* ===================================================================== */

/*!
 *  Print out help message.
 */
INT32 Usage()
{
    std::cerr << "This tool creates a register and memory access trace" << std::endl
              << "Specify the output trace file with -o" << std::endl
              << "Specify the number of instructions to skip before tracing with -s" << std::endl
              << "Specify the number of instructions to trace with -k" << std::endl
              << std::endl;

    std::cerr << KNOB_BASE::StringKnobSummary() << std::endl;

    return -1;
}

void print_trace_instr(trace_instr_format_t *instr)
{
    cout << "IP: 0x" << hex << instr->ip << dec << endl;

    cout << "has_mem: " << ((instr->has_mem_is_branch >> 1) & 1)
         << ", is_branch: " << (instr->has_mem_is_branch & 1) << endl;

    cout << "branch_taken: " << (int)instr->branch_taken << endl;

    cout << "Destination Registers: ";
    for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
        cout << (int)instr->destination_register[i] << " ";
    cout << endl;

    cout << "Source Registers: ";
    for (int i = 0; i < NUM_INSTR_SOURCES; i++)
        cout << (int)instr->source_register[i] << " ";
    cout << endl;

    // Memory addresses
    if (instr->source_memory_address) {
        cout << "Source Memory Addresses: ";
        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
            cout << "0x" << hex << instr->source_memory_address[i] << " ";
        cout << dec << endl;
    }

    if (instr->destination_memory_address) {
        cout << "Destination Memory Addresses: ";
        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
            cout << "0x" << hex << instr->destination_memory_address[i] << " ";
        cout << dec << endl;
    }

    // Memory sizes
    if (instr->source_memory_size) {
        cout << "Source Memory Sizes: ";
        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
            cout << (int)instr->source_memory_size[i] << " ";
        cout << endl;
    }

    if (instr->destination_memory_size) {
        cout << "Destination Memory Sizes: ";
        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
            cout << (int)instr->destination_memory_size[i] << " ";
        cout << endl;
    }
    cout << "---------------------" << endl;
}

/* ===================================================================== */
// Analysis routines
/* ===================================================================== */

void BeginInstruction(VOID *ip, uint32_t op_code, uint32_t numMemOperands, uint32_t ins_size, VOID *opstring)
{
    instrCount++;

    if(KnobSetMarkerMode.Value())
    {
        if(phase_seen[INFERENCE_FIRST_PASS_START])
        {
            if(phase_seen[INFERENCE_FIRST_PASS_END])
                tracing_on = false;
            else if(instrCount <= phase_instr[INFERENCE_FIRST_PASS_START] + KnobTraceInstructions.Value())
                tracing_on = true;
            else
                tracing_on = false;
        }
        else
        {
            tracing_on = false;
        }
    }
    else
    {
        if (instrCount > KnobSkipInstructions.Value())
        {
            tracing_on = true;
            if (instrCount > (KnobTraceInstructions.Value() + KnobSkipInstructions.Value()))
                tracing_on = false;
        }
    }    

    if (!tracing_on)
        return;

    curr_instr.ip = (unsigned long long int)ip;
    curr_instr.instr_size = (uint8_t) ins_size;

    bool hasMemory = (numMemOperands != 0);

    if (hasMemory)
    {
        curr_instr.has_mem_is_branch = 0b00000010;
    }
    else
    {
        curr_instr.has_mem_is_branch = 0;
    }
    curr_instr.branch_taken = 0;

    for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
    {
        curr_instr.destination_register[i] = 0;
    }

    for (int i = 0; i < NUM_INSTR_SOURCES; i++)
    {
        curr_instr.source_register[i] = 0;
    }

    // if (hasMemory)
    // {
        curr_instr.destination_memory_address = new unsigned long long int[NUM_INSTR_DESTINATIONS];
        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
            curr_instr.destination_memory_address[i] = 0;

        curr_instr.source_memory_address = new unsigned long long int[NUM_INSTR_SOURCES];
        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
            curr_instr.source_memory_address[i] = 0;

        curr_instr.destination_memory_size = new uint8_t[NUM_INSTR_DESTINATIONS];
        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
            curr_instr.destination_memory_size[i] = 0;

        curr_instr.source_memory_size = new uint8_t[NUM_INSTR_SOURCES];
        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
            curr_instr.source_memory_size[i] = 0;

        curr_instr.destination_memory_value = new unsigned char *[NUM_INSTR_DESTINATIONS];
        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
            curr_instr.destination_memory_value[i] = nullptr;

        curr_instr.source_memory_value = new unsigned char *[NUM_INSTR_SOURCES];
        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
            curr_instr.source_memory_value[i] = nullptr;
    // }
    // else
    // {
    //     curr_instr.destination_memory_address = nullptr;
    //     curr_instr.destination_memory_size = nullptr;
    //     curr_instr.destination_memory_value = nullptr;

    //     curr_instr.source_memory_address = nullptr;
    //     curr_instr.source_memory_size = nullptr;
    //     curr_instr.source_memory_value = nullptr;
    // }

    // memoryWriteIndex = -1;
    for(int i = 0; i < NUM_INSTR_SOURCES + NUM_INSTR_DESTINATIONS; i++)
        memOpToDestSlot[i] = -1;
}

void EndInstruction()
{
    if (debug)
        std::cout << "Done with instruction no: " << instrCount << std::endl;

    bool nonMarkerMode_endCondition = (instrCount > (KnobTraceInstructions.Value() + KnobSkipInstructions.Value()));
    bool markerMode_endCondition = (((phase_seen[INFERENCE_FIRST_PASS_START] == true) && ((phase_seen[INFERENCE_FIRST_PASS_END] == true) || (instrCount > phase_instr[INFERENCE_FIRST_PASS_START] + KnobTraceInstructions.Value())))
                                   || ((phase_seen[INFERENCE_FIRST_PASS_START] == false) && (instrCount > KnobTraceInstructions.Value()))); 

    if ((KnobSetMarkerMode.Value() == true && markerMode_endCondition == true) || (KnobSetMarkerMode.Value() == false && nonMarkerMode_endCondition == true))
    {
        if(KnobSetMarkerMode.Value() == true)
        {
            knob_trace_instr_count = instrCount - knob_skip_instr_count;
        }
        else
        {
            knob_trace_instr_count = instrCount - knob_skip_instr_count; // will be equal to KnobTraceInstructions.value()
        }

        tracing_on = false;

        if(KnobEnableTraceWriting.Value())
        {
            if (!output_file_closed)
            {
                fclose(out);
                output_file_closed = true;
            }
        }

        exit(0);
    }

    if(instrCount > knob_skip_instr_count)
    {
        // tracing_on = true;
        // cout << "Tracing on : " << instrCount << endl;

        if ((instrCount - knob_skip_instr_count) % 10000000 == 0)
        {
            std::cout << "Traced " << (instrCount - knob_skip_instr_count) << " instructions" << std::endl;
        }

        if (!skip_curr_instr)
        {
            // if(instrCount < 500010000) print_trace_instr(&curr_instr);
            if(KnobEnableTraceWriting.Value())
            {
                fwrite(&curr_instr.ip, sizeof(unsigned long long int), 1, out);
                fwrite(&curr_instr.has_mem_is_branch, sizeof(unsigned char), 1, out);
                fwrite(&curr_instr.branch_taken, sizeof(unsigned char), 1, out);
                fwrite(&curr_instr.instr_size, sizeof(uint8_t), 1, out);
                fwrite(curr_instr.destination_register, sizeof(unsigned char), NUM_INSTR_DESTINATIONS, out);
                fwrite(curr_instr.source_register, sizeof(unsigned char), NUM_INSTR_SOURCES, out);
            }
                
            if ((curr_instr.has_mem_is_branch & 0b00000010) == 2)
            {
                if(KnobEnableTraceWriting.Value())
                {
                    fwrite(curr_instr.destination_memory_address, sizeof(unsigned long long int), NUM_INSTR_DESTINATIONS, out);
                    fwrite(curr_instr.source_memory_address, sizeof(unsigned long long int), NUM_INSTR_SOURCES, out);
                    fwrite(curr_instr.destination_memory_size, sizeof(uint8_t), NUM_INSTR_DESTINATIONS, out);
                    fwrite(curr_instr.source_memory_size, sizeof(uint8_t), NUM_INSTR_SOURCES, out);
                }
            }

            for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
            {                
                if (curr_instr.destination_memory_size[i] > MAX_MEMORY_SIZE)
                {
                    std::cout << "More than MAX_MEMORY_SIZE(" << MAX_MEMORY_SIZE << ") traced. Error!" << std::endl;
                    exit(0);
                }
                if (curr_instr.destination_memory_size[i] > 0 && curr_instr.destination_memory_value[i] != nullptr)
                {
                    if(KnobEnableTraceWriting.Value())  
                        fwrite(curr_instr.destination_memory_value[i], curr_instr.destination_memory_size[i], 1, out);
                }
            }

            for (int i = 0; i < NUM_INSTR_SOURCES; i++)
            {
                if (curr_instr.source_memory_size[i] > MAX_MEMORY_SIZE)
                {
                    std::cout << "More than MAX_MEMORY_SIZE(" << MAX_MEMORY_SIZE << ") traced. Error!" << std::endl;
                    exit(0);
                }

                if (curr_instr.source_memory_size[i] > 0 && curr_instr.source_memory_value[i] != nullptr)
                {
                    if(KnobEnableTraceWriting.Value())      
                        fwrite(curr_instr.source_memory_value[i], curr_instr.source_memory_size[i], 1, out);
                }
            }
        }
        else
        {
            skip_curr_instr = false;
        }

        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
        {
            delete[] curr_instr.destination_memory_value[i];
            curr_instr.destination_memory_value[i] = nullptr;
        }

        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
        {
            delete[] curr_instr.source_memory_value[i];
            curr_instr.source_memory_value[i] = nullptr;
        }

        delete[] curr_instr.destination_memory_address;
        curr_instr.destination_memory_address = nullptr;
        delete[] curr_instr.source_memory_address;
        curr_instr.source_memory_address = nullptr;
        delete[] curr_instr.destination_memory_size;
        curr_instr.destination_memory_size = nullptr;
        delete[] curr_instr.source_memory_size;
        curr_instr.source_memory_size = nullptr;

        for(int i = 0; i < NUM_INSTR_SOURCES + NUM_INSTR_DESTINATIONS; i++)
            memOpToDestSlot[i] = -1;
    }
    else
    {
        if(instrCount % 10000000 == 0)
        {
            std::cout << "Skipped " << instrCount << " instructions" << std::endl;
        }
    }
}

void BranchOrNot(uint32_t taken)
{
    if(!tracing_on)
        return;
    curr_instr.has_mem_is_branch |= 0b00000001;
    if (taken != 0)
    {
        curr_instr.branch_taken = 1;
    }
}

void RegRead(uint32_t i, uint32_t index)
{
    if (!tracing_on)
        return;

    REG r = (REG)i;

    int already_found = 0;
    for (int i = 0; i < NUM_INSTR_SOURCES; i++)
    {
        if (curr_instr.source_register[i] == ((unsigned char)r))
        {
            already_found = 1;
            break;
        }
    }
    if (already_found == 0)
    {
        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
        {
            if (curr_instr.source_register[i] == 0)
            {
                curr_instr.source_register[i] = (unsigned char)r;
                break;
            }
        }
    }
}

void RegWrite(REG i, uint32_t index)
{
    if (!tracing_on)
        return;

    REG r = (REG)i;

    int already_found = 0;
    for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
    {
        if (curr_instr.destination_register[i] == ((unsigned char)r))
        {
            already_found = 1;
            break;
        }
    }
    if (already_found == 0)
    {
        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
        {
            if (curr_instr.destination_register[i] == 0)
            {
                curr_instr.destination_register[i] = (unsigned char)r;
                break;
            }
        }
    }
}

void MemoryRead(VOID *addr, uint32_t index, uint32_t read_size)
{
    if (!tracing_on)
        return;

    bool already_found = false;
    for (int i = 0; i < NUM_INSTR_SOURCES; i++)
    {
        if ((curr_instr.source_memory_address[i] == ((unsigned long long int)addr)) && (curr_instr.source_memory_size[i] == read_size))
        {
            already_found = true;
            break;
        }
    }

    if (!already_found)
    {
        for (int i = 0; i < NUM_INSTR_SOURCES; i++)
        {
            if (curr_instr.source_memory_address[i] == 0)
            {
                curr_instr.source_memory_address[i] = (unsigned long long int)addr;
                curr_instr.source_memory_size[i] = read_size;
                curr_instr.source_memory_value[i] = new unsigned char[read_size];

                uint32_t blocksize = 64;
                uint32_t offset = curr_instr.source_memory_address[i] & (blocksize - 1);

                if(read_size <= MAX_MEMORY_SIZE)
                {
                    if(offset + read_size > blocksize)
                    {
                        unalignedAccessCount++;
                    }
                }

                if (debug)
                    std::cout << "Instruction read " << read_size << " bytes at 0x" << std::hex << addr << std::endl;

                if (PIN_SafeCopy(curr_instr.source_memory_value[i], addr, read_size) == read_size)
                {
                    if (debug)
                    {
                        std::cout << "Obtained memory from 0x" << std::hex << addr << "with value ";
                        for (uint32_t j = 0; j < read_size; j++)
                        {
                            std::cout << std::hex << (int)curr_instr.source_memory_value[i][j];
                        }
                        std::cout << std::dec << std::endl;
                    }
                }
                else
                {
                    delete[] curr_instr.source_memory_value[i];
                    curr_instr.source_memory_address[i] = 0;
                    curr_instr.source_memory_value[i] = nullptr;
                    curr_instr.source_memory_size[i] = 0;

                    // if (debug)
                        std::cout << "Failed to obtain memory from 0x" << std::hex << addr << std::dec << std::endl;
                }

                break;
            }
        }
    }
}

void MemoryWriteCaptureAddress(VOID *addr, uint32_t index)
{
    if (!tracing_on)
        return;

    bool already_found = false;
    for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
    {
        // TODO:: I think may not happen?
        if (curr_instr.destination_memory_address[i] == ((unsigned long long int)addr))
        {
            already_found = true;
            break;
        }
    }

    if (!already_found)
    {
        for (int i = 0; i < NUM_INSTR_DESTINATIONS; i++)
        {
            if (curr_instr.destination_memory_address[i] == 0)
            {
                curr_instr.destination_memory_address[i] = (unsigned long long int)addr;
                // memoryWriteIndex = i;
                memOpToDestSlot[index] = i;
                break;
            }
        }
    }
}

void MemoryWriteCaptureValue(uint32_t index, uint32_t write_size)
{
    if (!tracing_on)
        return;

    if (memOpToDestSlot[index] != -1)
    {
        curr_instr.destination_memory_size[memOpToDestSlot[index]] = write_size;
        curr_instr.destination_memory_value[memOpToDestSlot[index]] = new unsigned char[write_size];
        unsigned long long int *addr = (unsigned long long int *)(curr_instr.destination_memory_address[memOpToDestSlot[index]]);

        if (curr_instr.destination_memory_address[memOpToDestSlot[index]] != 0 && write_size > 0)
        {
            uint32_t offset = curr_instr.destination_memory_address[memOpToDestSlot[index]] & 63;
            if (offset + write_size > 64)
            {
                unalignedAccessCount++;
            }
        }

        if (debug)
            std::cout << "Instruction wrote " << write_size << " bytes at 0x" << std::hex << addr << std::dec << std::endl;

        if (PIN_SafeCopy(curr_instr.destination_memory_value[memOpToDestSlot[index]], addr, write_size) == write_size)
        {
            if (debug)
            {
                std::cout << "Obtained memory from " << std::hex << addr << "with value ";
                for (uint32_t j = 0; j < write_size; j++)
                {
                    std::cout << std::hex << (int)curr_instr.destination_memory_value[memOpToDestSlot[index]][j];
                }
                std::cout << std::dec << std::endl;
            }
        }
        else
        {
            delete[] curr_instr.destination_memory_value[memOpToDestSlot[index]];
            curr_instr.destination_memory_address[memOpToDestSlot[index]] = 0;
            curr_instr.destination_memory_size[memOpToDestSlot[index]] = 0;
            curr_instr.destination_memory_value[memOpToDestSlot[index]] = nullptr;

            // if (debug)
                std::cout << "Failed to obtain memory from 0x" << std::hex << addr << std::endl;
        }

        // memoryWriteIndex = -1;
    }
    else
    {
        // if (debug)
            std::cout << "Memory write value instrumentation failed to find a memory write address" << std::endl;
    }
}

void MemoryWriteValueForCall(uint32_t size_of_call_instruction, uint32_t index)
{
    if (!tracing_on)
        return;

    // // TODO:: Check is memoryWriteIndex != -1, does it mean they don't want to consider? If yes, why even handle the case
    if (memOpToDestSlot[index] != -1)     
    // {
    //     curr_instr.destination_memory_size[memoryWriteIndex] = 0;
    //     curr_instr.destination_memory_value[memoryWriteIndex] = nullptr;
    //     memoryWriteIndex = -1;
    // }
    // else
    {
        curr_instr.destination_memory_size[memOpToDestSlot[index]] = 8;
        curr_instr.destination_memory_value[memOpToDestSlot[index]] = new unsigned char[8];
        unsigned long long int return_address = curr_instr.ip + size_of_call_instruction;
        // std::cout << "size of call instruction : " << size_of_call_instruction << std::endl;
        std::memcpy(curr_instr.destination_memory_value[memOpToDestSlot[index]], &return_address, 8);

        // memoryWriteIndex = -1;

        // if (debug)
        //     std::cout << "Memory write value for call instruction at 0x" << std::hex << curr_instr.ip
        //               << " with value " << return_address << std::dec << std::endl;
    }
    else
    {
        cout << "Memory write value for call instrumentation failed" << endl;
    }
}

// ── xchg bx,bx marker callback ───────────────────────────────────────────
// Called when Pin detects xchg bx,bx in the application.
// EAX holds the marker id (1-5).
VOID MarkerHit(UINT32 marker_id)
{
    if (marker_id == 0 || marker_id >= 6) return;
    if (phase_seen[marker_id]) return; // only record first occurrence

    phase_seen[marker_id]  = true;
    phase_instr[marker_id] = instrCount + 1;

    if(phase_seen[INFERENCE_FIRST_PASS_START])
        knob_skip_instr_count = instrCount;

    const char* names[] = {"", "PREPROCESSING_START", "PREPROCESSING_END",
                           "INFERENCE_PASS1_START", "INFERENCE_PASS1_END",
                           "INFERENCE_PASS2_END"};
    std::cout << ">>> MARKER " << marker_id << " [" << names[marker_id] << "]"
              << " at instrCount = " << instrCount + 1 << std::endl;    

    if (marker_id == PREPROCESSING_END && phase_seen[PREPROCESSING_START])
    {   
        std::cout << "    Preprocessing instructions: "<< ( phase_instr[PREPROCESSING_END] - phase_instr[PREPROCESSING_START]) << std::endl;    
    }

    if (marker_id == INFERENCE_FIRST_PASS_END && phase_seen[INFERENCE_FIRST_PASS_START])
    {
        UINT64 pass_len = phase_instr[INFERENCE_FIRST_PASS_END] - phase_instr[INFERENCE_FIRST_PASS_START];
        std::cout << "    One inference pass instructions: " << pass_len << std::endl;
    }

    // can be removed. As of now wont execute as we are ending after first pass end
    if (marker_id == INFERENCE_SECOND_PASS_END && phase_seen[INFERENCE_FIRST_PASS_START])
    {
        UINT64 two_passes = phase_instr[INFERENCE_SECOND_PASS_END] - phase_instr[INFERENCE_FIRST_PASS_START];
        std::cout << "    Two inference passes instructions: " << two_passes << std::endl;
    }
}

// // ── Function entry tracker (only active during skip phase) ───────────────
// VOID FuncEntry(CHAR* name)
// {
//     // print only during skip phase, every 50M instructions
//     if (!tracing_on && instrCount > 0 &&
//         instrCount - last_func_print_instr >= 50000000)
//     {
//         last_func_print_instr = instrCount;
//         std::cout << "[SKIP " << instrCount << "] in function: " << name << std::endl;
//     }
// }

/* ===================================================================== */
// Instrumentation callbacks
/* ===================================================================== */


// Is called for every instruction and instruments reads and writes
VOID Instruction(INS ins, VOID *v)
{
    uint32_t memOperands = INS_MemoryOperandCount(ins);
    // std::cout << std::endl;
    // std::cout << "memOperandscount = " << memOperands << std::endl ;

    // ── Detect xchg bx,bx marker ─────────────────────────────────────────
    // xchg bx,bx: opcode 0x87 DB with both operands being BX/RBX
    if (INS_Opcode(ins) == XED_ICLASS_XCHG &&
        INS_OperandCount(ins) >= 2 &&
        INS_OperandIsReg(ins, 0) && INS_OperandIsReg(ins, 1) &&
        (INS_OperandReg(ins, 0) == REG_BX || INS_OperandReg(ins, 0) == REG_RBX) &&
        (INS_OperandReg(ins, 1) == REG_BX || INS_OperandReg(ins, 1) == REG_RBX))
    {
        // Read marker id from EAX register value at runtime
        INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)MarkerHit,
                       IARG_REG_VALUE, REG_EAX,
                       IARG_CALL_ORDER, CALL_ORDER_FIRST,
                       IARG_END);
    }

    // // ── Track function names during skip phase ────────────────────────────
    // RTN rtn = INS_Rtn(ins);
    // if (RTN_Valid(rtn) && INS_Address(ins) == RTN_Address(rtn))
    // {
    //     std::string* name = new std::string(RTN_Name(rtn));
    //     INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)FuncEntry,
    //                    IARG_PTR, name->c_str(),
    //                    IARG_END);
    // }

    // begin each instruction with this function
    uint32_t opcode = INS_Opcode(ins);
    std::string opcodeStr = INS_Mnemonic(ins);
    // std::cout << "Opcode = " << opcode << " - " << opcodeStr << std::endl;
    INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)BeginInstruction,
                   IARG_INST_PTR,
                   IARG_UINT32, opcode,
                   IARG_UINT32, memOperands,
                   IARG_UINT32, INS_Size(ins), 
                   IARG_CALL_ORDER, CALL_ORDER_FIRST+1,
                   IARG_END);

    // instrument branch instructions
    if (INS_IsBranch(ins))
        INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)BranchOrNot,
                       IARG_BRANCH_TAKEN,
                       IARG_END);

    // instrument register reads
    uint32_t readRegCount = INS_MaxNumRRegs(ins);
    // std::cout << "readRegCount = " << readRegCount << std::endl;

    for (uint32_t i = 0; i < readRegCount; i++)
    {
        uint32_t regNum = INS_RegR(ins, i);

        INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)RegRead,
                       IARG_UINT32, regNum,
                       IARG_UINT32, i,
                       IARG_END);
    }

    // instrument register writes
    uint32_t writeRegCount = INS_MaxNumWRegs(ins);
    // std::cout << "writeRegCount = " << readRegCount << std::endl;

    for (uint32_t i = 0; i < writeRegCount; i++)
    {
        uint32_t regNum = INS_RegW(ins, i);

        INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)RegWrite,
                       IARG_UINT32, regNum,
                       IARG_UINT32, i,
                       IARG_END);
    }

    // instrument memory reads and writes

    // Iterate over each memory operand of the instruction.
    for (uint32_t memOp = 0; memOp < memOperands; memOp++)
    {
        if (INS_MemoryOperandIsRead(ins, memOp))
        {
            uint32_t read_size = INS_MemoryOperandSize(ins, memOp);
            if (read_size > MAX_MEMORY_SIZE)
            {
                // std::cout << "MemoryOperand is Read - " << memOp << ", size = " << read_size << std::endl;
                skip_curr_instr = true;
                skipInstructionCount++;
                readSkipInstrCount++;
                break;
            }

            INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)MemoryRead,
                           IARG_MEMORYOP_EA, memOp,
                           IARG_UINT32, memOp,
                           IARG_UINT32, read_size,
                           IARG_END);
        }

        if (INS_MemoryOperandIsWritten(ins, memOp))
        {
            uint32_t write_size = INS_MemoryOperandSize(ins, memOp);
            if (write_size > MAX_MEMORY_SIZE)
            {
                // std::cout << "MemoryOperand is Write - " << memOp << ", size = " << write_size << std::endl;
                skip_curr_instr = true;
                skipInstructionCount++;
                writeSkipInstrCount++;
                break;
            }
            INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)MemoryWriteCaptureAddress,
                           IARG_MEMORYOP_EA, memOp,
                           IARG_UINT32, memOp,
                           IARG_END);

            if (INS_HasFallThrough(ins))
            {
                INS_InsertCall(ins, IPOINT_AFTER, (AFUNPTR)MemoryWriteCaptureValue,
                               IARG_UINT32, memOp,
                               IARG_UINT32, write_size,
                               IARG_END);
            }
            else if (INS_IsCall(ins))
            {
                // std::cout << "MemoryOperand is Write but ISCall - " << memOp << std::endl;
                INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)MemoryWriteValueForCall, 
                               IARG_UINT32, INS_Size(ins),
                               IARG_UINT32, memOp,
                               IARG_END);
            }
            else
            {
                // if (debug)
                // {
                    std::cout << "Warning: Memory write instrumentation at IPOINT_AFTER for instruction ** " << INS_Disassemble(ins) << " ** is invalid" << std::endl;
                    std::cout << "Opcode: " << std::dec << INS_Opcode(ins) << std::endl;
                // }
            }
        }
    }

    // finalize each instruction with this function
    if (INS_HasFallThrough((ins)))
        INS_InsertCall(ins, IPOINT_AFTER, (AFUNPTR)EndInstruction,
                       IARG_CALL_ORDER, CALL_ORDER_LAST,
                       IARG_END);
    else
        INS_InsertCall(ins, IPOINT_BEFORE, (AFUNPTR)EndInstruction,
                       IARG_CALL_ORDER, CALL_ORDER_LAST,
                       IARG_END);
}

/*!
 * Print out analysis results.
 * This function is called when the application exits.
 * @param[in]   code            exit code of the application
 * @param[in]   v               value specified by the tool in the
 *                              PIN_AddFiniFunction function call
 */
VOID Fini(INT32 code, VOID *v)
{
    // close the file if it hasn't already been closed
    if (!output_file_closed)
    {
        fclose(out);
        output_file_closed = true;
    }
       std::cout << "\n========== TRACE GENERATION SUMMARY ==========" << std::endl;
    std::cout << "Total instructions executed:     " << instrCount << std::endl;
    std::cout << "Skip instructions :          " << knob_skip_instr_count << std::endl;
    std::cout << "Trace instructions:         " << knob_trace_instr_count << std::endl;

    std::cout << "\n--- Phase Boundaries (instrCount values) ---" << std::endl;
    const char* pnames[] = {"", "PREPROCESSING_START", "PREPROCESSING_END",
                            "INFERENCE_PASS1_START", "INFERENCE_PASS1_END",
                            "INFERENCE_PASS2_END"};
    for (int i = 1; i <= 5; i++)
    {    std::cout << "  Marker " << i << " [" << pnames[i] << "]: ";
        if (phase_seen[i])
            std::cout << phase_instr[i];
        else
            std::cout << "NOT SEEN";
        std::cout << std::endl;
    }

    if (phase_seen[PREPROCESSING_START] && phase_seen[PREPROCESSING_END])
        std::cout << "\nPreprocessing instructions:      "
                  << (phase_instr[PREPROCESSING_END] - phase_instr[PREPROCESSING_START]) << std::endl;

    if (phase_seen[INFERENCE_FIRST_PASS_START] && phase_seen[INFERENCE_FIRST_PASS_END])
    {
        UINT64 pass_len = phase_instr[INFERENCE_FIRST_PASS_END] - phase_instr[INFERENCE_FIRST_PASS_START];
        std::cout << "One inference pass instructions: " << pass_len << std::endl;
        std::cout << "\n--- Recommended ChampSim Settings ---" << std::endl;
        std::cout << "  ChampSim warmup:    " << 0.2 * pass_len
                  << "  (~20% of one pass)" << std::endl;
        std::cout << "  ChampSim simulate:  " << 0.8 * pass_len
                  << "  (remaining 80% of one pass)" << std::endl;
    }

    std::cout << "\n--- Memory Access Stats ---" << std::endl;
    std::cout << "Skip Instruction count = " << skipInstructionCount << std::endl;
    std::cout << "Skip Read Instruction count = " << readSkipInstrCount << std::endl;
    std::cout << "Skip Write Instruction count = " << writeSkipInstrCount << std::endl;
    std::cout << "Unaligned access count = " << unalignedAccessCount << std::endl;
    std::cout << "==============================================" << std::endl;
}

/*!
 * The main procedure of the tool.
 * This function is called when the application image is loaded but not yet started.
 * @param[in]   argc            total number of elements in the argv array
 * @param[in]   argv            array of command line arguments,
 *                              including pin -t <toolname> -- ...
 */
int main(int argc, char *argv[])
{
    // Initialize PIN library. Print help message if -h(elp) is specified
    // in the command line or the command line is invalid
    if (PIN_Init(argc, argv))
        return Usage();

    if (KnobEnableTraceWriting.Value())
    {
        const char *fileName = KnobOutputFile.Value().c_str();

        out = fopen(fileName, "wb");
        if (!out)
        {
            std::cout << "Couldn't open output trace file. Exiting." << std::endl;
            exit(1);
        }
    }
    else
    {
        out = nullptr;
    }    

    if(!KnobSetMarkerMode.Value())
        knob_skip_instr_count = KnobSkipInstructions.Value();

    // Register function to be called to instrument instructions
    INS_AddInstrumentFunction(Instruction, 0);

    // Register function to be called when the application exits
    PIN_AddFiniFunction(Fini, 0);

    // cerr <<  "===============================================" << endl;
    // cerr <<  "This application is instrumented by the Champsim Trace Generator" << endl;
    // cerr <<  "Trace saved in " << KnobOutputFile.Value() << endl;
    // cerr <<  "===============================================" << endl;

    // Start the program, never returns
    PIN_StartProgram();

    return 0;
}

/* ===================================================================== */
/* eof */
/* ===================================================================== */